services:
  - type: web
    name: coachbot-15j
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: DEFAULT_PROVIDER
        value: openai
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: DB_PATH
        value: /data/data.sqlite
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
